# Generated by Django 5.0.1 on 2026-07-07 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='adminuser',
            table='shop_admin',
        ),
        migrations.AlterModelTable(
            name='user',
            table='shop_user',
        ),
    ]
