# Generated by Django 5.0.1 on 2026-07-07 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_name', models.CharField(max_length=256, verbose_name='商品名称')),
                ('goods_image', models.CharField(blank=True, max_length=256, null=True, verbose_name='商品图片')),
                ('spec_name', models.CharField(blank=True, max_length=256, null=True, verbose_name='规格名称')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价')),
                ('quantity', models.IntegerField(verbose_name='数量')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='小计金额')),
            ],
            options={
                'verbose_name': '订单商品',
                'verbose_name_plural': '订单商品',
                'db_table': 'orders_orderitem',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=32, unique=True, verbose_name='订单编号')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='订单总金额')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='优惠金额')),
                ('pay_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='实付金额')),
                ('status', models.SmallIntegerField(choices=[(0, '待付款'), (1, '待发货'), (2, '待收货'), (3, '已完成'), (4, '已取消'), (5, '退款中')], default=0, verbose_name='订单状态')),
                ('pay_status', models.SmallIntegerField(choices=[(0, '未支付'), (1, '已支付'), (2, '退款中'), (3, '已退款')], default=0, verbose_name='支付状态')),
                ('pay_type', models.SmallIntegerField(blank=True, choices=[(1, '微信支付'), (2, '支付宝')], null=True, verbose_name='支付方式')),
                ('pay_time', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('ship_time', models.DateTimeField(blank=True, null=True, verbose_name='发货时间')),
                ('finish_time', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('cancel_time', models.DateTimeField(blank=True, null=True, verbose_name='取消时间')),
                ('remark', models.CharField(blank=True, max_length=512, null=True, verbose_name='用户备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='addresses.address', verbose_name='收货地址')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'db_table': 'orders_order',
            },
        ),
    ]
