# Generated by Django 5.0.1 on 2026-07-07 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='shop_order',
        ),
        migrations.AlterModelTable(
            name='orderitem',
            table='shop_orderitem',
        ),
    ]
