# Generated by Django 5.0.1 on 2026-07-07 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='分类名称')),
                ('level', models.SmallIntegerField(default=1, verbose_name='分类级别')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序号')),
                ('icon', models.CharField(blank=True, max_length=256, null=True, verbose_name='分类图标')),
                ('status', models.SmallIntegerField(default=1, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.category', verbose_name='父分类')),
            ],
            options={
                'verbose_name': '商品分类',
                'verbose_name_plural': '商品分类',
                'db_table': 'goods_category',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='商品名称')),
                ('sku', models.CharField(max_length=64, unique=True, verbose_name='SKU编码')),
                ('description', models.TextField(blank=True, null=True, verbose_name='商品描述')),
                ('images', models.JSONField(blank=True, null=True, verbose_name='商品图片')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='售价')),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='原价')),
                ('stock', models.IntegerField(default=0, verbose_name='库存')),
                ('sales', models.IntegerField(default=0, verbose_name='销量')),
                ('is_on_sale', models.BooleanField(default=True, verbose_name='是否上架')),
                ('is_hot', models.BooleanField(default=False, verbose_name='是否热门')),
                ('is_new', models.BooleanField(default=False, verbose_name='是否新品')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.category', verbose_name='分类')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'db_table': 'goods_goods',
            },
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='规格名称')),
                ('value', models.CharField(max_length=128, verbose_name='规格值')),
                ('price_offset', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='价格偏移')),
                ('stock', models.IntegerField(default=0, verbose_name='规格库存')),
                ('image', models.CharField(blank=True, max_length=256, null=True, verbose_name='规格图片')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.goods', verbose_name='商品')),
            ],
            options={
                'verbose_name': '商品规格',
                'verbose_name_plural': '商品规格',
                'db_table': 'goods_specification',
            },
        ),
    ]
