# Generated by Django 5.0.1 on 2026-07-07 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='shop_category',
        ),
        migrations.AlterModelTable(
            name='goods',
            table='shop_goods',
        ),
        migrations.AlterModelTable(
            name='specification',
            table='shop_specification',
        ),
    ]
