# Generated by Django 5.0.1 on 2026-07-07 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='任务标题')),
                ('description', models.TextField(blank=True, null=True, verbose_name='任务描述')),
                ('task_type', models.SmallIntegerField(choices=[(1, '数据同步'), (2, '邮件发送'), (3, '报表生成'), (4, '图片处理'), (5, '系统备份'), (6, '其他')], default=6, verbose_name='任务类型')),
                ('status', models.SmallIntegerField(choices=[(0, '待执行'), (1, '执行中'), (2, '已完成'), (3, '失败')], default=0, verbose_name='任务状态')),
                ('progress', models.IntegerField(default=0, verbose_name='进度(%)')),
                ('priority', models.SmallIntegerField(default=2, verbose_name='优先级(1-5)')),
                ('scheduled_time', models.DateTimeField(blank=True, null=True, verbose_name='计划执行时间')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始执行时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '任务',
                'verbose_name_plural': '任务',
                'db_table': 'shop_task',
                'ordering': ['-created_at'],
            },
        ),
    ]
