# Generated by Django 5.0.1 on 2026-07-07 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='优惠券名称')),
                ('coupon_type', models.SmallIntegerField(choices=[(1, '满减'), (2, '折扣'), (3, '无门槛')], verbose_name='优惠券类型')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='优惠金额')),
                ('discount_rate', models.DecimalField(decimal_places=2, default=1, max_digits=4, verbose_name='折扣率')),
                ('min_spend', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='最低消费金额')),
                ('total_count', models.IntegerField(verbose_name='总发放数量')),
                ('used_count', models.IntegerField(default=0, verbose_name='已使用数量')),
                ('per_user_limit', models.IntegerField(default=1, verbose_name='每人限领数量')),
                ('start_time', models.DateTimeField(verbose_name='生效时间')),
                ('end_time', models.DateTimeField(verbose_name='失效时间')),
                ('status', models.SmallIntegerField(default=1, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '优惠券',
                'verbose_name_plural': '优惠券',
                'db_table': 'coupons_coupon',
            },
        ),
        migrations.CreateModel(
            name='UserCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(0, '未使用'), (1, '已使用'), (2, '已过期')], default=0, verbose_name='状态')),
                ('receive_time', models.DateTimeField(auto_now_add=True, verbose_name='领取时间')),
                ('used_time', models.DateTimeField(blank=True, null=True, verbose_name='使用时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupons.coupon', verbose_name='优惠券')),
            ],
            options={
                'verbose_name': '用户优惠券',
                'verbose_name_plural': '用户优惠券',
                'db_table': 'coupons_usercoupon',
            },
        ),
    ]
