# Generated by Django 5.0.1 on 2026-07-07 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='coupon',
            table='shop_coupon',
        ),
        migrations.AlterModelTable(
            name='usercoupon',
            table='shop_usercoupon',
        ),
    ]
